### PR TITLE
Special handling for codeblocks 

### LINKED ISSUE #7: Do not render emojis in raw markdown blocks
Thanks for making this plugin!

I would like to add the following section to a developer guide in a `mdbook` generated documentation:

````
### `mdbook-emojicodes`

The following raw markdown:

```markdown
I love cats :cat: and dogs :dog:, I have two, one's gray, like a raccoon :raccoon:, and the other one is black, like the night :night_with_stars:.
```

will render as the following:

I love cats :cat: and dogs :dog:, I have two, one's gray, like a raccoon :raccoon:, and the other one is black, like the night :night_with_stars:.
````

---

This is how it renders on GitHub:

> ### `mdbook-emojicodes`
> 
> The following raw markdown:
> 
> ```markdown
> I love cats :cat: and dogs :dog:, I have two, one's gray, like a raccoon :raccoon:, and the other one is black, like the night :night_with_stars:.
> ```
> 
> will render as the following:
> 
> I love cats :cat: and dogs :dog:, I have two, one's gray, like a raccoon :raccoon:, and the other one is black, like the night :night_with_stars:.

This is how it renders in `mdbook`:

> image

---

Notice that in the markdown blocks in `mdbook` it still converts `:cat:` to :cat: but it doesn't do that on GitHub.

I think it would be nice if the plugin would leave any code blocks that are titled `markdown` alone. 

Initially I was thinking any code blocks should be left alone but then it wouldn't be possible to use emojicodes in admonish blocks using [`mdbook-admonish`](https://github.com/tommilligan/mdbook-admonish). 

Something else to consider is if someone has comments with `:tada:` in a `python` code block, should it be rendered as a emoji? Ideally it would be configurable per code block.

### PR DESCRIPTION
**Pull request by kdheepak**
Resolves #7

### CODE REVIEW

**Comment by blyxyas** [comment]
Could you split this changes into various commits? One for `rustfmt`, one for the main changes and one for tests so it can be reviewed more easily?

**Review by blyxyas — APPROVED** [review]
LGTM, Thanks! :heart:

**Comment by kdheepak** [comment]
Oops, sorry I didn’t get back to you on splitting the commits!

**Comment by kdheepak** [comment]
Thanks for merging the PR!

**Pull request merged**
